javac -d . Online.java
javac -d . Server.java
javac -d . ServerMain.java
javac -d . All_client.java
javac -d . Client.java
javac -d . Traitement.java
javac -d . Listener.java
javac -d . Start.java
javac -d . Main.java